// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Database.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Station.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Station TABLE
class TableStation extends SqfEntityTableBase {
  TableStation() {
    // declare properties of EntityTable
    tableName = 'stations';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('slug', DbType.text),
      SqfEntityFieldBase('type', DbType.text),
      SqfEntityFieldBase('way', DbType.text),
      SqfEntityFieldBase('line', DbType.text),
      SqfEntityFieldBase('destination', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableStation();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class StationsModel extends SqfEntityModelProvider {
  StationsModel() {
    databaseName = myDbModel.databaseName;
    databaseTables = [
      TableStation.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Station
class Station {
  Station(
      {this.id,
      this.name,
      this.slug,
      this.type,
      this.way,
      this.line,
      this.destination,
      this.isDeleted}) {
    _setDefaultValues();
  }
  Station.withFields(this.name, this.slug, this.type, this.way, this.line,
      this.destination, this.isDeleted) {
    _setDefaultValues();
  }
  Station.withId(this.id, this.name, this.slug, this.type, this.way, this.line,
      this.destination, this.isDeleted) {
    _setDefaultValues();
  }
  Station.fromMap(Map<String, dynamic> o) {
    id = o['id'] as int;
    name = o['name'] as String;
    slug = o['slug'] as String;
    type = o['type'] as String;
    way = o['way'] as String;
    line = o['line'] as String;
    destination = o['destination'] as String;
    isDeleted = o['isDeleted'] != null ? o['isDeleted'] == 1 : null;
  }
  // FIELDS (Station)
  int id;
  String name;
  String slug;
  String type;
  String way;
  String line;
  String destination;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Station)

  static const bool _softDeleteActivated = true;
  StationManager __mnStation;

  StationManager get _mnStation {
    return __mnStation = __mnStation ?? StationManager();
  }

  // METHODS
  Map<String, dynamic> toMap({bool forQuery = false, bool forJson = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (slug != null) {
      map['slug'] = slug;
    }

    if (type != null) {
      map['type'] = type;
    }

    if (way != null) {
      map['way'] = way;
    }

    if (line != null) {
      map['line'] = line;
    }

    if (destination != null) {
      map['destination'] = destination;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChilds(
      [bool forQuery = false, bool forJson = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (slug != null) {
      map['slug'] = slug;
    }

    if (type != null) {
      map['type'] = type;
    }

    if (way != null) {
      map['way'] = way;
    }

    if (line != null) {
      map['line'] = line;
    }

    if (destination != null) {
      map['destination'] = destination;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method always returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method always returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChilds(false, true));
  }

  List<dynamic> toArgs() {
    return [id, name, slug, type, way, line, destination, isDeleted];
  }

  static Future<List<Station>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Station.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Station>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Station>[];
    try {
      objList = list
          .map((station) => Station.fromMap(station as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Station.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Station>> fromObjectList(Future<List<dynamic>> o) async {
    final data = await o;
    return await Station.fromMapList(data);
  }

  static Future<List<Station>> fromMapList(List<dynamic> data) async {
    final List<Station> objList = <Station>[];
    for (final Map map in data as List<Map>) {
      final obj = Station.fromMap(map as Map<String, dynamic>);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Station by ID if exist, otherwise returns null
  /// <param name='id'>Primary Key Value</param>
  /// <returns>returns Station if exist, otherwise returns null
  Future<Station> getById(int id) async {
    if (id == null) {
      return null;
    }
    Station obj;
    final data = await _mnStation.getById(id);
    if (data.length != 0) {
      obj = Station.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnStation.insert(this);
    } else {
      id = await _upsert();
    }

    return id;
  }

  /// saveAs Station. Returns a new Primary Key value of Station

  /// <returns>Returns a new Primary Key value of Station
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Station> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  Future<List<BoolResult>> saveAll(List<Station> stations) async {
    final results = _mnStation.saveAll(
        'INSERT OR REPLACE INTO stations (id,  name, slug, type, way, line, destination,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
        stations);
    return results;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> _upsert() async {
    try {
      id = await _mnStation.rawInsert(
          'INSERT OR REPLACE INTO stations (id,  name, slug, type, way, line, destination,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
          [id, name, slug, type, way, line, destination, isDeleted]);
      saveResult = BoolResult(
          success: true, successMessage: 'Station id=$id updated successfuly');
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Station Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Station>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a <List<BoolResult>>
  Future<List<BoolResult>> upsertAll(List<Station> stations) async {
    final results = await _mnStation.rawInsertAll(
        'INSERT OR REPLACE INTO stations (id,  name, slug, type, way, line, destination,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
        stations);
    return results;
  }

  /// Deletes Station

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Station invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnStation
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnStation.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Station>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Station invoked (id=$id)');
    {
      return _mnStation.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  //private StationFilterBuilder _Select;
  StationFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return StationFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  StationFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return StationFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion station

// region StationField
class StationField extends SearchCriteria {
  StationField(this.stationFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  StationFilterBuilder stationFB;

  StationField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  StationFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param, SqlSyntax.EQuals,
            stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param, SqlSyntax.NotEQuals,
            stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.EQualsOrNull, stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder isNull() {
    stationFB._addedBlocks = setCriteria(
        0,
        stationFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      stationFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          stationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          stationFB._addedBlocks);
      _waitingNot = '';
      stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
          stationFB._addedBlocks.retVal;
    }
    return stationFB;
  }

  StationFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      stationFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          stationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          stationFB._addedBlocks);
      _waitingNot = '';
      stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
          stationFB._addedBlocks.retVal;
      stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
          stationFB._addedBlocks.retVal;
    }
    return stationFB;
  }

  StationFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      stationFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          stationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          stationFB._addedBlocks);
      _waitingNot = '';
      stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
          stationFB._addedBlocks.retVal;
    }
    return stationFB;
  }

  StationFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      stationFB._addedBlocks = setCriteria(
          pFirst,
          stationFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          stationFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        stationFB._addedBlocks = setCriteria(pFirst, stationFB.parameters,
            param, SqlSyntax.LessThan, stationFB._addedBlocks);
      } else {
        stationFB._addedBlocks = setCriteria(pFirst, stationFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, stationFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        stationFB._addedBlocks = setCriteria(pLast, stationFB.parameters, param,
            SqlSyntax.GreaterThan, stationFB._addedBlocks);
      } else {
        stationFB._addedBlocks = setCriteria(pLast, stationFB.parameters, param,
            SqlSyntax.LessThanOrEquals, stationFB._addedBlocks);
      }
    }
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.GreaterThan, stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.LessThanOrEquals, stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param, SqlSyntax.LessThan,
            stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param, SqlSyntax.LessThan,
            stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    stationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.LessThanOrEquals, stationFB._addedBlocks)
        : setCriteria(pValue, stationFB.parameters, param,
            SqlSyntax.GreaterThan, stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }

  StationFilterBuilder inValues(dynamic pValue) {
    stationFB._addedBlocks = setCriteria(
        pValue,
        stationFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        stationFB._addedBlocks);
    _waitingNot = '';
    stationFB._addedBlocks.needEndBlock[stationFB._blockIndex] =
        stationFB._addedBlocks.retVal;
    return stationFB;
  }
}
// endregion StationField

// region StationFilterBuilder
class StationFilterBuilder extends SearchCriteria {
  StationFilterBuilder(Station obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Station _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  StationFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  StationFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  StationFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  StationFilterBuilder where(String whereCriteria) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter();
      _addedBlocks =
          setCriteria(0, parameters, param, '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  StationFilterBuilder page(int page, int pagesize) {
    if (page > 0) _page = page;
    if (pagesize > 0) _pagesize = pagesize;
    return this;
  }

  /// int count = LIMIT
  StationFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  StationFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  StationFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  StationFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s desc ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  StationFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') groupByList.add(' $s ');
        }
      }
    }
    return this;
  }

  StationField setField(StationField field, String colName, DbType dbtype) {
    return StationField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  StationField _id;
  StationField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  StationField _name;
  StationField get name {
    return _name = setField(_name, 'name', DbType.text);
  }

  StationField _slug;
  StationField get slug {
    return _slug = setField(_slug, 'slug', DbType.text);
  }

  StationField _type;
  StationField get type {
    return _type = setField(_type, 'type', DbType.text);
  }

  StationField _way;
  StationField get way {
    return _way = setField(_way, 'way', DbType.text);
  }

  StationField _line;
  StationField get line {
    return _line = setField(_line, 'line', DbType.text);
  }

  StationField _destination;
  StationField get destination {
    return _destination = setField(_destination, 'destination', DbType.text);
  }

  StationField _isDeleted;
  StationField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Station._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Station> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();
    if (Station._softDeleteActivated && !hardDelete) {
      r = await _obj._mnStation.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnStation.delete(qparams);
    }
    return r;
  }

  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Station bulk invoked');
    return _obj._mnStation.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from stations ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnStation.updateBatch(qparams, values);
  }

  /// This method always returns StationObj if exist, otherwise returns null
  /// <returns>List<Station>
  Future<Station> toSingle([VoidCallback Function(Station o) station]) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnStation.toList(qparams);
    final data = await objFuture;
    Station obj;
    if (data.isNotEmpty) {
      obj = Station.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    if (station != null) {
      station(obj);
    }
    return obj;
  }

  /// This method always returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) stationCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final stationsFuture = await _obj._mnStation.toList(qparams);
    final int count = stationsFuture[0]['CNT'] as int;
    if (stationCount != null) {
      stationCount(count);
    }
    return count;
  }

  /// This method always returns List<Station>.
  /// <returns>List<Station>
  Future<List<Station>> toList(
      [VoidCallback Function(List<Station> o) stationList]) async {
    final data = await toMapList();
    final List<Station> stationsData = await Station.fromMapList(data);
    if (stationList != null) stationList(stationsData);
    return stationsData;
  }

  /// This method always returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method always returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChilds(false, true));
    }
    return json.encode(list);
  }

  /// This method always returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnStation.toList(qparams);
  }

  /// Returns List<DropdownMenuItem<Station>>
  Future<List<DropdownMenuItem<Station>>> toDropDownMenu(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<Station>> o)
          dropDownMenu]) async {
    _buildParameters();
    final stationsFuture = _obj._mnStation.toList(qparams);

    final data = await stationsFuture;
    final int count = data.length;
    final List<DropdownMenuItem<Station>> items = []..add(DropdownMenuItem(
        value: Station(),
        child: Text('Select Station'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: Station.fromMap(data[i] as Map<String, dynamic>),
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// Returns List<DropdownMenuItem<int>>
  Future<List<DropdownMenuItem<int>>> toDropDownMenuInt(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<int>> o)
          dropDownMenu]) async {
    _buildParameters();
    qparams.selectColumns = ['id', displayTextColumn];
    final stationsFuture = _obj._mnStation.toList(qparams);

    final data = await stationsFuture;
    final int count = data.length;
    final List<DropdownMenuItem<int>> items = []..add(DropdownMenuItem(
        value: 0,
        child: Text('Select Station'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: data[i]['id'] as int,
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// This method always returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) _buildParameters();
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnStation.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject(
      [VoidCallback Function(List<dynamic> o) listObject]) async {
    _buildParameters();

    final objectFuture = _obj._mnStation.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    if (listObject != null) {
      listObject(objectsData);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Station.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnStation.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion StationFilterBuilder

// region StationFields
class StationFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField _fSlug;
  static TableField get slug {
    return _fSlug = _fSlug ?? SqlSyntax.setField(_fSlug, 'slug', DbType.text);
  }

  static TableField _fType;
  static TableField get type {
    return _fType = _fType ?? SqlSyntax.setField(_fType, 'type', DbType.text);
  }

  static TableField _fWay;
  static TableField get way {
    return _fWay = _fWay ?? SqlSyntax.setField(_fWay, 'way', DbType.text);
  }

  static TableField _fLine;
  static TableField get line {
    return _fLine = _fLine ?? SqlSyntax.setField(_fLine, 'line', DbType.text);
  }

  static TableField _fDestination;
  static TableField get destination {
    return _fDestination = _fDestination ??
        SqlSyntax.setField(_fDestination, 'destination', DbType.text);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion StationFields

//region StationManager
class StationManager extends SqfEntityProvider {
  StationManager()
      : super(StationsModel(), tableName: _tableName, colId: _colId);
  static String _tableName = 'stations';
  static String _colId = 'id';
}

//endregion StationManager
class StationsModelSequenceManager extends SqfEntityProvider {
  StationsModelSequenceManager() : super(StationsModel());
}
// END OF ENTITIES
